include_guard()

function(make_plugin NAME)
    if(EMSCRIPTEN)
        set(PLUGIN_LIBRARY_TYPE STATIC)
    else()
        set(PLUGIN_LIBRARY_TYPE SHARED)
    endif()
    add_library(${NAME} ${PLUGIN_LIBRARY_TYPE})
    target_sources(${NAME} PRIVATE ${ARGN})
    target_compile_definitions(${NAME} PUBLIC PLUGIN_SHARED PLUGIN_EXPORT)
    set_target_properties(${NAME} PROPERTIES PREFIX "lib")
    set_property(TARGET ${NAME} PROPERTY POSITION_INDEPENDENT_CODE ON)
endfunction()